import Head from 'next/head'
import Image from 'next/image'
import Dashboard from '../components/Dashboard'
import NavBar from '../components/NavBar'
import SideBar from '../components/SideBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Starbucks Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <NavBar />
      </header>

      <main className='bg-[#E5E5E6]'>
        <SideBar />
      </main>
    </div>
  )
}
